/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.viatra.cep.mqtt.midl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MIDLUiModule extends AbstractMIDLUiModule {
}
