/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.viatra.cep.mqtt.midl.tests

import com.google.inject.Inject
import org.eclipse.viatra.cep.mqtt.midl.mIDL.IoTSystem
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MIDLInjectorProvider)
class MIDLParsingTest{

	@Inject
	ParseHelper<IoTSystem> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
