/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.viatra.cep.mqtt.midl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class MIDLScopeProvider extends AbstractMIDLScopeProvider {

}
